package gui;

import java.awt.Color;

public class ReportWindow extends javax.swing.JFrame {

    String[] data;

    /**
     * Creates new form ReportWindow
     */
    public ReportWindow(String[] data) {
        this.data = data;
        setTitle("Reporte ID: " + data[0]);
        setVisible(true);

        initComponents();
        modifyColorDisabled();

        cleanData();
        fillData();
    }

    private void modifyColorDisabled() {
        txtName.setDisabledTextColor(Color.black);
        txtName.setDisabledTextColor(Color.black);
        txtDate.setDisabledTextColor(Color.black);
        txtHour.setDisabledTextColor(Color.black);
        txtNeighborhood.setDisabledTextColor(Color.black);
        txtObject.setDisabledTextColor(Color.black);
        txtModusOperandi.setDisabledTextColor(Color.black);
        txtPlace.setDisabledTextColor(Color.black);
        txtDescription.setDisabledTextColor(Color.black);
    }

    private void cleanData() {
        lblTitle.setText("Reporte #");
        txtName.setText("");
        txtDate.setText("");
        txtHour.setText("");
        txtNeighborhood.setText("");
        txtObject.setText("");
        txtModusOperandi.setText("");
        txtPlace.setText("");
        txtDescription.setText("");
    }

    private void fillData() {
        lblTitle.setText("Reporte #" + data[0]);
        txtName.setText(data[1]);
        txtDate.setText(data[2]);
        txtHour.setText(data[3]);
        txtNeighborhood.setText(data[4]);
        txtObject.setText(data[5]);
        txtModusOperandi.setText(data[6]);
        txtPlace.setText(data[7]);
        txtDescription.setText(data[8]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblHour = new javax.swing.JLabel();
        txtHour = new javax.swing.JTextField();
        lblNeighborhood = new javax.swing.JLabel();
        txtNeighborhood = new javax.swing.JTextField();
        lblObject = new javax.swing.JLabel();
        txtObject = new javax.swing.JTextField();
        lblModusOperandi = new javax.swing.JLabel();
        txtModusOperandi = new javax.swing.JTextField();
        lblPlace = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPlace = new javax.swing.JTextArea();
        lblDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(780, 500));
        setMinimumSize(new java.awt.Dimension(780, 500));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("ReportWindow"); // NOI18N
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Reporte #id");

        lblName.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblName.setText("Nombre:");

        txtName.setEnabled(false);

        lblDate.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblDate.setText("Fecha: ");

        txtDate.setEnabled(false);

        lblHour.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblHour.setText("Hora: ");

        txtHour.setEnabled(false);

        lblNeighborhood.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblNeighborhood.setText("Localidad: ");

        txtNeighborhood.setEnabled(false);

        lblObject.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblObject.setText("Objeto: ");

        txtObject.setEnabled(false);

        lblModusOperandi.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblModusOperandi.setText("Modalidad: ");

        txtModusOperandi.setEnabled(false);

        lblPlace.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblPlace.setText("Descripción del lugar: ");

        txtPlace.setEditable(false);
        txtPlace.setColumns(20);
        txtPlace.setRows(5);
        txtPlace.setEnabled(false);
        jScrollPane2.setViewportView(txtPlace);

        lblDescription.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblDescription.setText("Descripción del hecho: ");

        txtDescription.setEditable(false);
        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setEnabled(false);
        jScrollPane1.setViewportView(txtDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNeighborhood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModusOperandi)
                                    .addComponent(lblObject, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(txtObject, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtName)
                                        .addComponent(txtDate)
                                        .addComponent(txtModusOperandi)
                                        .addComponent(txtHour, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNeighborhood, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlace)
                            .addComponent(lblDescription))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHour)
                    .addComponent(txtHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNeighborhood)
                    .addComponent(txtNeighborhood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObject)
                    .addComponent(txtObject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModusOperandi)
                    .addComponent(txtModusOperandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlace)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblModusOperandi;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNeighborhood;
    private javax.swing.JLabel lblObject;
    private javax.swing.JLabel lblPlace;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtHour;
    private javax.swing.JTextField txtModusOperandi;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNeighborhood;
    private javax.swing.JTextField txtObject;
    private javax.swing.JTextArea txtPlace;
    // End of variables declaration//GEN-END:variables
}
